# Generated by Django 4.2.21 on 2025-06-30 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manufactured_products',
            fields=[
                ('m_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='our_product',
            fields=[
                ('product_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=1000)),
                ('units', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('col_allo_stat', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('NOT_ALLOCATED', 'Not Allocated')], default='NOT_ALLOCATED', max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.manufactured_products')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=60)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=60)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.stock')),
            ],
        ),
        migrations.AddField(
            model_name='manufactured_products',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.our_product'),
        ),
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=300)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.users')),
            ],
        ),
    ]
