# Generated by Django 4.2.21 on 2025-06-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
