# Generated by Django 4.2.21 on 2025-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_stock_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('unit_size', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('allocated', models.FloatField()),
                ('sold', models.FloatField()),
                ('remaining', models.FloatField()),
            ],
        ),
    ]
