# Generated by Django 4.2.21 on 2025-09-17 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_user_stock_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_stock_record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
