# Generated by Django 4.2.21 on 2025-07-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('units', models.CharField(max_length=250)),
                ('total_quantity', models.IntegerField(max_length=250)),
            ],
            options={
                'db_table': 'product_stock2',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.our_product'),
            preserve_default=False,
        ),
    ]
