# Generated by Django 4.2.21 on 2025-07-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_inventory_sales_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufactured_products',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product_name',
        ),
        migrations.AddField(
            model_name='allocation',
            name='man_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.manufactured_products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufactured_products',
            name='total',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
