# Generated by Django 4.2.21 on 2025-07-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_product_name_manufactured_products_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.users'),
            preserve_default=False,
        ),
    ]
