# Generated by Django 4.2.21 on 2025-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_expense_category_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactured_products',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
