# Generated by Django 4.2.21 on 2025-07-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_manufactured_products_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
