# Generated by Django 4.2.21 on 2025-08-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactured_products',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
