# Generated by Django 4.2.21 on 2025-08-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_manufactured_products_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.users')),
            ],
        ),
    ]
