web: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py shell -c 
"from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'doubleportion')" && gunicorn Youthproject.wsgi:application
