web: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput &&
 python manage.py create_superuser_if_not_exists python manage.py runserver 0.0.0.0:$PORT

